# vim: syntax=config

vo=gpu
gpu-context=auto

profile=opengl-hq

ontop
autofit-larger=100%x95%

msg-module
msg-color
term-osd-bar

osd-level=1
osd-duration=2500
osd-status-msg='${time-pos} / ${duration}${?percent-pos: (${percent-pos}%)}${?frame-drop-count:${!frame-drop-count==0: Dropped: ${frame-drop-count}}}\n${?chapter:Chapter: ${chapter}}'

screenshot-format=png
screenshot-png-compression=8
screenshot-template='/tmp/%F_%p'

#############
# Languages #
#############

slang=el,gr,en,eng             		# automatically select these subtitles (decreasing priority)
alang=en,eng,el,gr		        # automatically select these audio tracks (decreasing priority)


#########
# Audio #
#########

audio-file-auto=fuzzy                   # external audio doesn't has to match the file name exactly to autoload
audio-pitch-correction=yes              # automatically insert scaletempo when playing with higher speed
volume-max=200                          # maximum volume in %, everything above 100 results in amplification
volume=100                              # default volume, 100 = unchanged


[extension.jpg]
pause

[extension.JPG]
pause

[extension.jpeg]
pause

[extension.JPEG]
pause

[extension.png]
pause

[extension.PNG]
pause

[extension.tif]
pause

[extension.TIF]
pause

[extension.tiff]
pause

[extension.TIFF]
pause

[extension.gif]
loop-file=inf

[extension.GIF]
loop-file=inf

[extension.gifv]
loop-file=inf

[extension.GIFV]
loop-file=inf

