# vim: syntax=config

vo=gpu
gpu-context=wayland
gpu-api=auto

profile=gpu-hq

ontop
no-border
autofit-larger=100%x95%

msg-module
msg-color
term-osd-bar

osd-level=1
osd-duration=2500
osd-status-msg='${time-pos} / ${duration}${?percent-pos: (${percent-pos}%)}${?frame-drop-count:${!frame-drop-count==0: Dropped: ${frame-drop-count}}}\n${?chapter:Chapter: ${chapter}}'

screenshot-format=png
screenshot-png-compression=8
screenshot-template='/tmp/%F_%p'

sub-auto=fuzzy
slang=el,gr,en,eng
alang=en,eng,el,gr

audio-file-auto=fuzzy
audio-pitch-correction=yes
volume-max=200
volume=100

[extension.jpg]
pause

[extension.JPG]
pause

[extension.jpeg]
pause

[extension.JPEG]
pause

[extension.png]
pause

[extension.PNG]
pause

[extension.tif]
pause

[extension.TIF]
pause

[extension.tiff]
pause

[extension.TIFF]
pause

[extension.gif]
loop-file=inf

[extension.GIF]
loop-file=inf

[extension.gifv]
loop-file=inf

[extension.GIFV]
loop-file=inf

