set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

set -gw aggressive-resize on
set -g mouse off
set -g base-index 1
set -gw pane-base-index 1
set -g renumber-windows on
set -gw monitor-activity on
set -g history-limit 50000

set -sg escape-time 0
set -gw mode-keys vi
set -g status-keys vi
set -g prefix C-space
unbind C-b
bind C-space send-prefix
unbind Space
bind Space last-window
bind C new-window -c '#{pane_current_path}'
unbind '"'
unbind n
bind n split-window -v
bind C-n split-window -v -b
bind N split-window -v -c '#{pane_current_path}'
unbind %
unbind v
bind v split-window -h
bind C-v split-window -h -b
bind V split-window -h -c '#{pane_current_path}'
bind Escape copy-mode
bind C-u copy-mode -u
unbind p
bind p paste-buffer
bind C-p choose-buffer
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'C-v' send -X rectangle-toggle
bind-key -T copy-mode-vi 'y' send -X copy-selection
bind-key -T copy-mode-vi 'Space' send -X halfpage-down
bind-key -T copy-mode-vi 'Bspace' send -X halfpage-up
bind Y run 'tmux show-buffer | xsel -i -b'
bind P run 'tmux set-buffer -- "$(xsel -o -b)"; tmux paste-buffer'
bind u last-pane
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r H resize-pane -L
bind -r J resize-pane -D
bind -r K resize-pane -U
bind -r L resize-pane -R
bind -r M-h resize-pane -L 5
bind -r M-j resize-pane -D 5
bind -r M-k resize-pane -U 5
bind -r M-l resize-pane -R 5
bind -r C-j select-pane -t :.+
bind -r C-k select-pane -t :.-
bind -r C-l next-window
bind -r C-h previous-window
bind / command-prompt -p "search:" "find-window '%%'"
bind m command-prompt -p "monitor:" "set -gw monitor-content '%%'"

set -g status-interval 5
set -g status-justify centre
set -g display-time 4000
set -g status-left "#{?client_prefix,#[bg=yellow]#[fg=black],}[#S]"
set -g status-right "[%d-%b|%R]"
set -gw window-status-format '#I:#W#F'
set -gw window-status-current-format '#I:[#P]#W#F'

source-file "${HOME}/.config/tmux/tmux-colors-solarized/tmuxcolors-dark.conf"
set-option -g pane-border-fg cyan
set-option -g pane-active-border-fg yellow
set-window-option -g window-status-attr dim
set-window-option -g window-status-current-attr bright
