refresh_interval = 1000

[[modules]]
name = "window"
instance = "0"
format = "{title}  [{app_name}]"
html_escape = false

[modules.on_click]
WheelDown = [
	"swayr",
	"next-window",
	"current-workspace",
]
Right = [
	"swayr",
	"switch-to-urgent-or-lru-window",
]
WheelUp = [
	"swayr",
	"prev-window",
	"current-workspace",
]
Left = [
	"swaymsg",
	"scratchpad",
	"show",
]

[[modules]]
name = "sysinfo"
instance = "0"
format = "CPU:{cpu_usage:{:5.1}}%, RAM:{mem_usage:{:5.1}}%, L:{load_avg_1:{:5.2}} {load_avg_5:{:5.2}} {load_avg_15:{:5.2}}"
html_escape = false

[modules.on_click]
Right = [
	"footclient",
	"sudo",
	"htop",
]
Left = [
	"footclient",
	"htop",
]

[[modules]]
name = "battery"
instance = "0"
format = "Bat:{state_of_charge:{:5.1}}% /{state_of_health:{:5.1}}% {state}"
html_escape = false

[modules.on_click]
Right = [
	"footclient",
	"watch",
	"sensors",
]
Left = [
	"footclient",
	"watch",
	"acpi -V",
]

[[modules]]
name = "wpctl"
instance = "0"
format = "Vol:{volume:{:3}}%{muted}"
html_escape = true

[modules.on_click]
WheelDown = [
	"wpctl",
	"set-volume",
	"@DEFAULT_AUDIO_SINK@",
	"1%-",
]
Right = [
	"wpctl",
	"set-mute",
	"@DEFAULT_AUDIO_SINK@",
	"toggle",
]
WheelUp = [
	"wpctl",
	"set-volume",
	"@DEFAULT_AUDIO_SINK@",
	"1%+",
]
Left = [
	"footclient",
	"watch",
	"wpctl",
	"status",
]

[[modules]]
name = "date"
instance = "0"
format = "%F %X"
html_escape = false

[modules.on_click]
Left = [
	"footclient",
	"-H",
	"cal -3",
]
