c.backend = 'webengine'
c.colors.completion.category.bg = 'qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #073642, stop:1 #002B36)'
c.colors.completion.category.border.bottom = '#002B36'
c.colors.completion.category.border.top = '#073642'
c.colors.completion.category.fg = '#93A1A1'
c.colors.completion.even.bg = '#002B36'
c.colors.completion.fg = '#657B83'
c.colors.completion.item.selected.bg = '#586E75'
c.colors.completion.item.selected.border.bottom = '#002B36'
c.colors.completion.item.selected.border.top = '#073642'
c.colors.completion.item.selected.fg = '#002B36'
c.colors.completion.match.fg = '#2AA198'
c.colors.completion.odd.bg = '#073642'
c.colors.completion.scrollbar.bg = '#002B36'
c.colors.completion.scrollbar.fg = '#657B83'
c.colors.downloads.bar.bg = '#073642'
c.colors.downloads.error.bg = '#002B36'
c.colors.downloads.error.fg = '#D33682'
c.colors.downloads.start.bg = '#002B36'
c.colors.downloads.start.fg = '#6C71C4'
c.colors.downloads.stop.bg = '#002B36'
c.colors.downloads.stop.fg = '#268BD2'
c.colors.hints.bg = 'qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(7, 54, 66, 0.8), stop:1 rgba(0, 43, 54, 0.8))'
c.colors.hints.fg = '#FDF6E3'
c.colors.hints.match.fg = '#B58900'
c.colors.keyhint.bg = 'rgba(0, 43, 53, 80%)'
c.colors.keyhint.fg='#839496'
c.colors.keyhint.suffix.fg = '#B58900'
c.colors.messages.error.bg = '#073642'
c.colors.messages.error.border = '#586E75'
c.colors.messages.error.fg = '#DC322F'
c.colors.messages.info.bg = '#073642'
c.colors.messages.info.border = '#586E75'
c.colors.messages.info.fg = '#B58900'
c.colors.messages.warning.bg = '#073642'
c.colors.messages.warning.border = '#586E75'
c.colors.messages.warning.fg = '#CB4B16'
c.colors.prompts.bg = '#002B36'
c.colors.prompts.border = '1px solid #586E75'
c.colors.prompts.fg = '#93A1A1'
c.colors.prompts.selected.bg = '#586E75'
c.colors.statusbar.caret.bg = '#002b36'
c.colors.statusbar.caret.fg = '#B58900'
c.colors.statusbar.caret.selection.bg = '#002B36'
c.colors.statusbar.caret.selection.fg = '#268BD2'
c.colors.statusbar.command.bg = '#073642'
c.colors.statusbar.command.fg = '#93A1A1'
c.colors.statusbar.command.private.bg = '#6C71C4'
c.colors.statusbar.command.private.fg = '#93A1A1'
c.colors.statusbar.insert.bg = '#002B36'
c.colors.statusbar.insert.fg = '#B58900'
c.colors.statusbar.normal.bg = '#002B36'
c.colors.statusbar.normal.fg = '#93A1A1'
c.colors.statusbar.passthrough.bg = '#002b36'
c.colors.statusbar.passthrough.fg = '#B58900'
c.colors.statusbar.private.bg = '#6C71C4'
c.colors.statusbar.private.fg = '#93A1A1'
c.colors.statusbar.progress.bg = '#93A1A1'
c.colors.statusbar.url.error.fg = '#DC322F'
c.colors.statusbar.url.fg = '#93A1A1'
c.colors.statusbar.url.hover.fg = '#268BD2'
c.colors.statusbar.url.success.http.fg = '#2AA198'
c.colors.statusbar.url.success.https.fg = '#859900'
c.colors.statusbar.url.warn.fg = '#D33682'
c.colors.tabs.bar.bg = '#002B36'
c.colors.tabs.even.bg = '#073642'
c.colors.tabs.even.fg = '#839496'
c.colors.tabs.indicator.error = '#DC322F'
c.colors.tabs.indicator.start = '#B58900'
c.colors.tabs.indicator.stop = '#2AA198'
c.colors.tabs.indicator.system = 'rgb'
c.colors.tabs.odd.bg = '#002B36'
c.colors.tabs.odd.fg = '#839496'
c.colors.tabs.selected.even.bg = '#839496'
c.colors.tabs.selected.even.fg = '#002B36'
c.colors.tabs.selected.odd.bg = '#839496'
c.colors.tabs.selected.odd.fg = '#002B36'
c.content.javascript.enabled = False
c.downloads.position = 'bottom'
c.fonts.completion.category = 'bold 14px monospace'
c.fonts.completion.entry = '14px monospace'
c.fonts.debug_console = '14px monospace'
c.fonts.downloads = '14px monospace'
c.fonts.hints = 'bold 14px monospace'
c.fonts.keyhint = '14px monospace'
c.fonts.messages.error = '14px monospace'
c.fonts.messages.info = '14px monospace'
c.fonts.messages.warning = '14px monospace'
c.fonts.monospace = 'xos4 Terminus'
c.fonts.prompts = '14px monospace'
c.fonts.statusbar = '14px monospace'
c.fonts.tabs = '14px monospace'
c.hints.border = '1px solid #2AA198'
c.tabs.new_position.unrelated = 'next'
c.tabs.select_on_remove = 'prev'
c.window.hide_decoration = True
config.bind(',L', 'spawn zsh -c "echo {url} >> /tmp/linklist"')
config.bind(',M', 'spawn mpv --no-terminal --force-window --keep-open {url}')
config.bind(',l', 'spawn zsh -c "echo {url} | xsel -i -b"')
config.bind(',m', 'spawn mpv --no-terminal --force-window --keep-open {url}')
config.bind(',v', 'spawn you-get -p "mpv --no-terminal --force-window --keep-open" {url}')
config.bind(';L', 'hint links spawn zsh -c "echo {hint-url} >> /tmp/linklist"')
config.bind(';M', 'hint links spawn mpv --no-terminal --force-window --keep-open {hint-url}')
config.bind(';l', 'hint links spawn zsh -c "echo {hint-url} | xsel -i -b"')
config.bind(';m', 'hint links spawn mpv --no-terminal --force-window --keep-open {hint-url}')
config.bind(';v', 'hint links spawn you-get -p "mpv --no-terminal --force-window --keep-open" {hint-url}')
config.set('content.javascript.enabled', True, '*://github.com/*')
config.set('content.javascript.enabled', True, '*://gitlab.com/*')
config.set('content.javascript.enabled', True, '*://mail.google.com/*')
config.set('content.javascript.enabled', True, '*://mail.protonmail.com/*')
config.set('content.javascript.enabled', True, '*://www.inoreader.com/*')
